### ISSUE TITLE
hw1 CI cannot test python0

### ISSUE THREAD

**Issue by tigercosmos** [yungyuc/nsdhw_20sp#20]
see the log in https://github.com/yungyuc/nsdhw_20sp/runs/500966947
seems when the error occurs in the sub-process, the CI cannot find it.
cc @yungyuc

**Comment by yungyuc** [comment]
I tend to say to exercise the right granted to the grader (at the end of https://github.com/yungyuc/nsdhw_20sp/tree/master/hw1/README.rst):

> The grader reserves the right to modify the final score according to the student's implementation.

Is there a good way to check for a random error like this?  The validation script is already 2 or 3 times longer than the answer.

**Comment by tigercosmos** [comment]
yep. I think more efforts on this are sort of trivial works. I rather like to check it by eyes.
That's why I add ***"The grader reserves the right to modify the final score according to the student's implementation."*** today.

**Comment by yungyuc** [comment]
Let’s go with manual inspection, before we can find a clever way to improve the coverage.

It’s a pretty good example that tests don’t capture every error.  If we had tweaked the question it might be possible, but that’s not the real world.
