### ISSUE TITLE
hw2/validate.sh

### ISSUE THREAD

**Issue by AilurusUmbra** [yungyuc/nsdhw_20sp#35]
Some question about [`validate.sh`](https://github.com/yungyuc/nsdhw_20sp/blob/master/hw2/validate.sh) in hw2 repo.

* What do the scripts at line 115~117 want to test?
  * May I ask which package contains the `_vector` module? or `_vector` should be generated by pybind? 
```
echo "import the extension module:"
python3 -c 'import _vector ; print(_vector)' ; ret=$?
if [ $ret -ne 0 ] ; then echo "failure" ; exit 1 ; fi
```
* Why are there `exit 0` at line 140 and at line 145?
  * It seems that these two `exit 0` might skip the following validating scripts.

**Comment by yungyuc** [comment]
`_vector` is the module that you are requested to create using `pybind11`.  https://github.com/yungyuc/nsdhw_20sp/blob/master/hw2/validate.sh#L116 makes sure your module can be imported to Python.

The two `exit 0` are a bug.  Thanks for spotting it.

**Comment by yungyuc** [comment]
Feel free to reopen if you need further discussion.  Thanks again for the bug report.

**Comment by AilurusUmbra** [comment]
Thanks a lot!
