### ISSUE TITLE
Do we merge hw1 back to master?

### ISSUE THREAD

**Issue by yungyuc** [yungyuc/nsdhw_20sp#50]
@tigercosmos Do you want to merge `hw1` branch back to `master`?

**Comment by tigercosmos** [comment]
basically I don't think it's necessary to do so, but we can still do that.
btw. a student's PR is wrong, so I just copied his code and rejected his PR.

**Comment by yungyuc** [comment]
Thanks.  It's good to keep `hw?` free.  We can keep it that way.

I will remind students to keep PRs correct.  If they need help let's discuss how to do it in telegram.
