### ISSUE TITLE
HW3: performance measurement

### ISSUE THREAD

**Issue by csvt32745** [yungyuc/nsdhw_20sp#54]
https://github.com/yungyuc/nsdhw_20sp/blob/hw3/hw3/validate.py#L179

This validation program will measure the performance and output "performance.txt".

Do we still need to do measurement ourselves as mentioned in the 4th grading spec ?
Also, if we output "performance.txt", this file will be over-written by that validation program.

> 4. Time the two multiplication functions and compare the performance. Then output performance.txt. The format of performance.txt can be any. Just make it reasonable. (1 point)

Thanks~

**Comment by yungyuc** [comment]
You should measure it yourself and include `performance.txt` in the submission.  The file will be included in your PR so that grader will be able to inspect.  The validating script does not push back to the repository.

**Comment by csvt32745** [comment]
Got it, thanks!
