### ISSUE TITLE
hw3 performance.txt

### ISSUE THREAD

**Issue by AilurusUmbra** [yungyuc/nsdhw_20sp#60]
In [hw3 instructions](https://github.com/yungyuc/nsdhw_20sp/blob/master/hw3/README.rst#additional-notes-on-grading), we are asked to output `performance.txt`, 
while `validate.py` would output another `performance.txt` (see [here](https://github.com/yungyuc/nsdhw_20sp/blob/master/hw3/validate.py#L179)).
I guess `validate.py` would overwrite `performance.txt` later.

**Comment by csvt32745** [comment]
I think it's the same question as mine in #54  XD

**Comment by AilurusUmbra** [comment]
Thanks, I forgot to check previous issues QQ
