### ISSUE TITLE
Missing question mark in hw4 validate.py

### ISSUE THREAD

**Issue by yanagiragi** [yungyuc/nsdhw_20sp#82]
It seems to be missing a '?" in [here](https://github.com/yungyuc/nsdhw_20sp/blob/master/hw4/validate.py#L34) ? I guess it should be '$?' instead.

Log:
```
./validate.py: line 35: [: $: integer expression expected
```

**Comment by yungyuc** [comment]
Fixed in https://github.com/yungyuc/nsdhw_20sp/commit/8c1cb3edfe67281fd8e7016985013e1fea4a55ac .  Thanks for the report.
